/**
 * DO NOT EDIT MANUALLY
 * Single Source of Truth: courses/courses-manifest.json
 * Re-exports generated course data generated by scripts/generate-courses.ts
 */
export * from './generated/course-data';
export * from './generated/lesson-loaders';
export { BUILTIN_LESSONS, BUILTIN_LESSONS as COURSE_LESSONS } from './generated/course-data-full';
