import fs from 'fs';
import path from 'path';

const manifestPath = path.resolve(process.cwd(), 'courses/courses-manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));

const level7Lessons = [
  {
    id: '01-ci-cd-concept',
    title: 'CI/CD là gì? Tự động hóa tích hợp & chuyển giao liên tục',
    duration: 25,
    xp: 80,
    prerequisites: ['15-professional-team-project'],
    labIds: ['first-workflow'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '02-github-actions-intro',
    title: 'GitHub Actions là gì? Nền tảng tự động hóa của GitHub',
    duration: 25,
    xp: 80,
    prerequisites: ['01-ci-cd-concept'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '03-workflow-architecture',
    title: 'Kiến trúc Workflow: Events, Jobs, Steps và Runners',
    duration: 30,
    xp: 90,
    prerequisites: ['02-github-actions-intro'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '04-workflow-yaml-syntax',
    title: '.github/workflows và cú pháp YAML chuẩn',
    duration: 30,
    xp: 90,
    prerequisites: ['03-workflow-architecture'],
    labIds: ['first-workflow'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '05-events-and-triggers',
    title: 'Sự kiện kích hoạt (Events & Triggers: push, pull_request, workflow_dispatch)',
    duration: 30,
    xp: 90,
    prerequisites: ['04-workflow-yaml-syntax'],
    labIds: ['push-trigger'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '06-jobs-configuration',
    title: 'Cấu hình Jobs: runs-on, phân tách độc lập và môi trường',
    duration: 30,
    xp: 95,
    prerequisites: ['05-events-and-triggers'],
    labIds: ['multi-job'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '07-steps-execution',
    title: 'Các bước thực thi (Steps): name, id và thứ tự tuần tự',
    duration: 30,
    xp: 90,
    prerequisites: ['06-jobs-configuration'],
    labIds: ['failing-test'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '08-runners-environment',
    title: 'Môi trường thực thi Runners: GitHub-hosted vs Self-hosted',
    duration: 30,
    xp: 95,
    prerequisites: ['07-steps-execution'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '09-run-vs-uses',
    title: 'Phân biệt run (shell command) vs uses (prebuilt action)',
    duration: 30,
    xp: 90,
    prerequisites: ['08-runners-environment'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '10-env-variables',
    title: 'Biến môi trường (Environment Variables) cấp workflow, job và step',
    duration: 30,
    xp: 90,
    prerequisites: ['09-run-vs-uses'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '11-contexts-and-expressions',
    title: 'Contexts & Expressions: ${{ github.ref }}, matrix và toán tử',
    duration: 30,
    xp: 95,
    prerequisites: ['10-env-variables'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '12-job-dependencies-needs',
    title: 'Quan hệ phụ thuộc giữa các Job với thuộc tính needs',
    duration: 30,
    xp: 95,
    prerequisites: ['11-contexts-and-expressions'],
    labIds: ['job-needs'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '13-conditional-execution-if',
    title: 'Thực thi có điều kiện với if: always(), success(), failure()',
    duration: 30,
    xp: 90,
    prerequisites: ['12-job-dependencies-needs'],
    labIds: ['conditional-step'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '14-matrix-strategy',
    title: 'Chiến lược ma trận kiểm thử đa môi trường (Matrix Strategy)',
    duration: 35,
    xp: 100,
    prerequisites: ['13-conditional-execution-if'],
    labIds: ['matrix-build'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '15-artifacts-sharing',
    title: 'Lưu trữ và chia sẻ sản phẩm build với Artifacts',
    duration: 30,
    xp: 95,
    prerequisites: ['14-matrix-strategy'],
    labIds: ['artifact-sharing'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '16-secrets-and-variables',
    title: 'Bảo mật thông tin nhạy cảm với Secrets và Secret Masking',
    duration: 30,
    xp: 95,
    prerequisites: ['15-artifacts-sharing'],
    labIds: ['secret-redaction'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '17-pull-request-ci',
    title: 'Thiết lập CI Pipeline tự động kiểm thử trên Pull Request',
    duration: 35,
    xp: 100,
    prerequisites: ['16-secrets-and-variables'],
    labIds: ['pr-ci', 'protected-branch-check'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '18-environments-and-deployment',
    title: 'Môi trường triển khai (Environments) & Cổng phê duyệt Protection Rules',
    duration: 35,
    xp: 110,
    prerequisites: ['17-pull-request-ci'],
    labIds: ['environment-deploy'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '19-reusable-workflows',
    title: 'Tái sử dụng luồng công việc với Reusable Workflows (workflow_call)',
    duration: 35,
    xp: 110,
    prerequisites: ['18-environments-and-deployment'],
    labIds: ['reusable-workflow'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '20-ci-cd-capstone',
    title: 'Capstone Project: Xây dựng hoàn chỉnh CI/CD Pipeline cho Web Application',
    duration: 50,
    xp: 250,
    prerequisites: ['18-environments-and-deployment', '19-reusable-workflows'],
    labIds: ['release-pipeline', 'ci-cd-capstone'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
];

const level8Lessons = [
  {
    id: '01-git-internals-intro',
    title: 'Git Internals là gì? Bí mật dưới nắp ca-pô của Git',
    duration: 25,
    xp: 85,
    prerequisites: ['20-ci-cd-capstone'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '02-porcelain-vs-plumbing',
    title: 'Phân biệt Porcelain Commands vs Plumbing Commands',
    duration: 25,
    xp: 85,
    prerequisites: ['01-git-internals-intro'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '03-dot-git-directory',
    title: 'Khám phá cấu trúc bên trong thư mục .git',
    duration: 30,
    xp: 90,
    prerequisites: ['02-porcelain-vs-plumbing'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '04-object-database',
    title: 'Cơ sở dữ liệu đối tượng Git (Object Database)',
    duration: 35,
    xp: 100,
    prerequisites: ['03-dot-git-directory'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '05-content-addressable-storage',
    title: 'Bộ nhớ định danh theo nội dung (Content-Addressable Storage)',
    duration: 30,
    xp: 95,
    prerequisites: ['04-object-database'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '06-blob-object',
    title: 'Đối tượng Blob: Lưu trữ nội dung nhị phân và tệp tin',
    duration: 30,
    xp: 90,
    prerequisites: ['05-content-addressable-storage'],
    labIds: ['hash-object-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '07-tree-object',
    title: 'Đối tượng Tree: Lưu trữ cấu trúc thư mục và quyền tệp',
    duration: 35,
    xp: 95,
    prerequisites: ['06-blob-object'],
    labIds: ['write-tree-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '08-commit-object',
    title: 'Đối tượng Commit: Ghi lại snapshot lịch sử và metadata tác giả',
    duration: 35,
    xp: 100,
    prerequisites: ['07-tree-object'],
    labIds: ['commit-tree-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '09-tag-object',
    title: 'Đối tượng Tag: Đánh dấu phiên bản có chú thích (Annotated Tag)',
    duration: 30,
    xp: 90,
    prerequisites: ['08-commit-object'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '10-git-hash-object',
    title: 'Tạo và băm đối tượng thủ công với git hash-object',
    duration: 35,
    xp: 100,
    prerequisites: ['09-tag-object'],
    labIds: ['hash-object-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '11-git-cat-file',
    title: 'Giải mã và kiểm tra chi tiết đối tượng với git cat-file',
    duration: 30,
    xp: 95,
    prerequisites: ['10-git-hash-object'],
    labIds: ['cat-file-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '12-references-and-heads',
    title: 'Cơ chế References (Refs): heads, tags và remotes',
    duration: 30,
    xp: 90,
    prerequisites: ['11-git-cat-file'],
    labIds: ['update-ref-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '13-symbolic-refs-head',
    title: 'Con trỏ HEAD & Symbolic References trong .git/HEAD',
    duration: 30,
    xp: 90,
    prerequisites: ['12-references-and-heads'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '14-git-index-internals',
    title: 'Cấu trúc tệp nhị phân .git/index (Staging Area Internals)',
    duration: 35,
    xp: 95,
    prerequisites: ['13-symbolic-refs-head'],
    labIds: ['update-index-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '15-revision-syntax',
    title: 'Cú pháp tra cứu Revision chuyên sâu: HEAD~, HEAD^, HEAD^2',
    duration: 35,
    xp: 95,
    prerequisites: ['14-git-index-internals'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '16-object-graph-traversal',
    title: 'Duyệt đồ thị đối tượng có hướng (Directed Acyclic Graph)',
    duration: 35,
    xp: 100,
    prerequisites: ['15-revision-syntax'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '17-packfiles-and-deltas',
    title: 'Đóng gói Packfiles và nén sai biệt Delta Compression',
    duration: 35,
    xp: 95,
    prerequisites: ['16-object-graph-traversal'],
    labIds: ['git-gc-pack-lab'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '18-refspec-and-remotes',
    title: 'Cấu trúc Refspec và đồng bộ Remote References',
    duration: 30,
    xp: 90,
    prerequisites: ['17-packfiles-and-deltas'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '19-reflog-internals',
    title: 'Cơ chế lưu trữ và phục hồi của .git/logs (Reflog Internals)',
    duration: 35,
    xp: 100,
    prerequisites: ['18-refspec-and-remotes'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
  {
    id: '20-build-commit-manually-capstone',
    title: 'Capstone: Tự tay tạo Commit hoàn chỉnh chỉ bằng Plumbing Commands',
    duration: 50,
    xp: 250,
    prerequisites: ['18-refspec-and-remotes', '19-reflog-internals'],
    labIds: ['internals-manual-commit-capstone'],
    completion: { theoryViewed: true, quiz: { minimumScore: 75 } },
  },
];

for (const mod of manifest.curriculum) {
  if (mod.id === '07-github-actions') {
    mod.status = 'active';
    mod.lessons = level7Lessons;
    console.log(`Updated 07-github-actions: active with ${level7Lessons.length} lessons`);
  }
  if (mod.id === '08-git-internals') {
    mod.status = 'active';
    mod.lessons = level8Lessons;
    console.log(`Updated 08-git-internals: active with ${level8Lessons.length} lessons`);
  }
}

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf-8');
console.log('✅ courses-manifest.json updated successfully!');
